### ISSUE TITLE
WsImport Ant task, with fork="true", does not work with JDK1.6

### ISSUE THREAD

**Issue by glassfishrobot** [javaee/metro-wsit#365]
When we use the b07 promoted WSIT with GF b33c and JDK1.6, the WsImport ant task
does not run throwing a NoClassDefFoundError. This happens irrespective of the
OS. The endorsed directory has webservices-api.jar in place both in JDK1.6 and
GF 9.1 endorsed directories.
This is a regression in this build.

Following Kohsuke's blog, I tried removing webservices-api.jar, but still faced
the same issue.

Also, following the checkin messages, we tried using
com.sun.tools.ws.ant.WsImport2 ant task, instead of
com.sun.tools.ws.ant.WsImport and it worked.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[current]
